# Read the documentation at https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
service: leeds-talk-blog

provider:
    lambdaHashingVersion: 20201221
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: eu-west-2 # London
    # The stage of the application, e.g. dev, production, staging… ('dev' is the default)
    stage: dev
    runtime: provided.al2
    environment:
        # Symfony environment variables
        APP_ENV: prod

plugins:
  - ./vendor/bref/bref
  - serverless-lift

functions:
    # This function runs the Symfony website/API
    web:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-80-fpm}
        events:
            - httpApi: '*'
    # This function let us run console commands in Lambda
    console:
        handler: bin/console
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-80} # PHP
            - ${bref:layer.console} # The "console" layer

constructs:
    website:
        type: server-side-website
        assets:
            '/build/*': public/build
            '/favicon.ico': public/favicon.ico
            '/apple-touch-icon.png': public/apple-touch-icon.png
            '/robots.txt': public/robots.txt

package:
    patterns:
        # Excluded files and folders for deployment
        - '!assets/**'
        - '!node_modules/**'
        - '!public/build/**'
        - '!tests/**'
        - '!var/**'
        # If you want to include files and folders that are part of excluded folders,
        # add them at the end
        - 'var/cache/prod/**'
        - 'public/build/entrypoints.json'
        - 'public/build/manifest.json'
